### ISSUE TITLE
How do I install inside docker?

### ISSUE THREAD

**Issue by rubo77** [jellyfin/jellyfin-plugin-bookshelf#110]
this is my docke-compose.yaml:

```
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /media/movies
        target: /media/movies
      - type: bind
        source: /media/music
        target: /media/music
        read_only: false
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.eclabs.de
```

How would I include this plugin inside docker?
